spring.application.name=auth-back
spring.docker.compose.enabled=false
jwt.secret-key=${JWT_SECRET_KEY}
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration