services:
  auth_app:
    image: auth_back:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - auth_db
    networks:
      - auth_network
  auth_db:
    image: mysql:8.0
    env_file:
      - .env
    volumes:
      - ./init_db_scripts/schema_db.sql:/docker-entrypoint-initdb.d/schema_db.sql
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "${MYSQL_USER}", "-p${MYSQL_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - auth_network

volumes:
  db_data:
networks:
  auth_network:
    driver: bridge